### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by JStika** [contributte/datagrid#1002]
https://examples.contributte.org/datagrid-skeleton/ is dead?

**Comment by f3l1x** [comment]
Hi. Why do you think?

![Screenshot 2021-12-07 at 10 51 11](https://user-images.githubusercontent.com/538058/145006587-5e26640f-313a-4ec4-b3d2-dc38e728e6fd.png)

**Comment by JStika** [comment]
I see 2 days yet on url https://examples.contributte.org/packages/datagrid/actions
![Clipboard01](https://user-images.githubusercontent.com/722942/145020430-eb1e3168-97f0-4a4c-83cb-0812e8fd0433.jpg)

**Comment by paveljanda** [comment]
I can see also 404

**Comment by f3l1x** [comment]
Oh I see. It's old URL. I've fixed redirects. Thank you.
