### ISSUE TITLE
FilterDateRange and change in items per page

### ISSUE THREAD

**Issue by Michal-Szekeres** [contributte/datagrid#1014]
Hello,
If you try to filter items in grid with FilterDateRange, it works well, but then if you change items per page, for example from 20 to 50, you can see, that the item count at the bottom is not the same anymore and if you try to reload the page, the value in FilterDateRange input is no longer there. The problem seems to be in function "createComponentFilter" in setting up the validationScope on "perPage_submit", so I made a workaround, simply overload "createComponentFilter" function and set validation scope to NULL, until there is a proper solution:

```
	public function createComponentFilter(): Form
	{
		$form = parent::createComponentFilter();
		$form['perPage_submit']->setValidationScope(NULL);
		return $form;
	}
```

**Comment by f3l1x** [comment]
Solved via #1001 and #997.
