### ISSUE TITLE
Make DataGrid::addColumn public for custom columns

### ISSUE THREAD

**Issue by juniwalk** [contributte/datagrid#1043]
Would it be possible to make the ```DataGrid::addColumn``` method public so anyone could create custom column logic and use it within DataGrid?

**Comment by radimvaculik** [comment]
@juniwalk What type of column do you miss? Maybe we should implement it directly into Datagrid.

**Comment by juniwalk** [comment]
@radimvaculik This is what I did by the way [AbstractGrid::addColumnEnum](https://github.com/juniwalk/utils/blob/main/src/UI/DataGrids/AbstractGrid.php#L87)

I also needed to edit Row class, so right now I am using fork of DataGrid which is not great.
![image](https://user-images.githubusercontent.com/451918/233570516-710bb076-11ce-4266-9001-3f608765c395.png)

**Comment by radimvaculik** [comment]
Could you prepare a PR for it, please? Against `next` branch.

**Comment by juniwalk** [comment]
That Row class modification? Sure, right on.
