### ISSUE TITLE
Rename package name from `Ublaboo` to `Contributte`

### ISSUE THREAD

**Issue by radimvaculik** [contributte/datagrid#1067]
It's obvious from the title.

```php
- namespace Ublaboo\DataGrid;
+ namespace Contributte\Datagrid;
```

**Comment by radimvaculik** [comment]
@paveljanda @f3l1x Could you please give your opinion? Thanks.

**Comment by paveljanda** [comment]
Yep, I agree, you can send a PR 👍

**Comment by radimvaculik** [comment]
@lilianalillyy Could you prepare a PR on `next` branch with `compatibility.php` file? 🙏

**Comment by lilianalillyy** [comment]
Sure!

**Comment by lilianalillyy** [comment]
@radimvaculik Sorry it took so long but PR is opened now :)
