### ISSUE TITLE
Wrong display of toolbar & export buttons

### ISSUE THREAD

**Issue by elring** [contributte/datagrid#1101]
After commit 55fd8b4  the toolbar look wrong:

![image](https://github.com/contributte/datagrid/assets/24586123/ba4c5c31-e184-43bf-8015-779718f1f82c)

1. The buttons are without any space between - this is because of now wrong CSS selector in datagrid.css - extra div is now needed - line 74 should be changed to:
```
.datagrid .datagrid-toolbar > div > span > a {
  margin-left: 0.5em;
}

```

2. The export buttons are on new line - this is because of the new snippet div - the export toolbar is outside of it. This can be solved either by moving the export toolbar into the new snippet or by css "hack" of the snippet div:

```
.datagrid .datagrid-toolbar > div {
  display: inline-block;
}
```

After these changes, toolbar looks better:

![image](https://github.com/contributte/datagrid/assets/24586123/46de41a5-ae68-494b-9911-40c6d79b2dfb)

Should I make PR (which way for 2)?

**Comment by paveljanda** [comment]
1) Yes, pls create a new MR, thanks! 👍 
2) I am not sure I follow - what do you mean by which way for 2?

**Comment by paveljanda** [comment]
Thx 👍
