### ISSUE TITLE
DataAttribute for InlineAdd and InlineEdit

### ISSUE THREAD

**Issue by rendix2** [contributte/datagrid#1107]
Hi,

is possible to add `setDataAttribute()` for InlineEdit and InlineAdd like in Actions? Thank you

**Comment by radimvaculik** [comment]
@rendix2 Could you prepare a pull request based on `next` branch? Thanks.

**Comment by rendix2** [comment]
@radimvaculik Yeah I created PR. Can you merge it please?

**Comment by f3l1x** [comment]
Merged
