### ISSUE TITLE
Too many 3rd party dependencies on frontend

### ISSUE THREAD

**Issue by matronator** [contributte/datagrid#1118]
There's so many dependencies, OMG! It would be great to reduce the number of packages needed to install, or at the very least create some meta-package containing all the packages needed, so the user only has to `npm install` one package and not 30...

**Comment by f3l1x** [comment]
It would be great. Who is willing to reduce it? Are you?

**Comment by paveljanda** [comment]
Question is, are you looking at the `master` branch or `next`?

**Comment by matronator** [comment]
> Question is, are you looking at the `master` branch or `next`?

`master`

**Comment by paveljanda** [comment]
Ok. Then I suggest:

1) loking at `next` branch
2) you offering a feasible solution how to reduce the number of dependencies

Thx

**Comment by paveljanda** [comment]
Closing as there was no other comment
