### ISSUE TITLE
bug in master/v7: per-page autosubmit working only once

### ISSUE THREAD

**Issue by paveljanda** [contributte/datagrid#1122]
Affected version: master/v7

Bug description: after changing the autosubmit select from 10 to 20, the form autosubmits, but when using for the second time, it does not work neither it triggeres any AJAX call.

I uspect the select is not reinitialised after the first redraw of the component.

The functionality was previously (v6) taken care by following jQuery logic: https://github.com/contributte/datagrid/blob/v6.x/assets/datagrid.js#L154

**Comment by f3l1x** [comment]
Should be fixed https://github.com/contributte/datagrid/commit/92e44349a43827d9e0eeeb0cb822da38602c2a93
