### ISSUE TITLE
Manual page number selection via number input with confirm button.

### ISSUE THREAD

**Issue by kolacekp** [contributte/datagrid#1124]
Hello,
it would be very useful to have the extended pagination feature, where I could enter the page number manually (let's say I want to go to page 20, I will type number 20 into small input and then hit "go" button).

**Comment by radimvaculik** [comment]
@kolacekp Could you introduce a pull request with changes, please? 🙏

**Comment by radimvaculik** [comment]
@kolacekp Or you can have custom template for paginator (see `DatagridPaginator::setTemplateFile()` or `Datagrid::setCustomPaginatorTemplate()`), where you can have your custom form.

**Comment by kolacekp** [comment]
@radimvaculik thanks, but I can't find that anywhere in documentation.

**Comment by radimvaculik** [comment]
It isn't documented very well. Check the source code.

**Comment by radimvaculik** [comment]
@kolacekp 👀 https://github.com/contributte/datagrid/pull/1135/files

**Comment by kolacekp** [comment]
@radimvaculik thanks! I will look into that :)
