### ISSUE TITLE
fixedcolumns - možnost zafixovat sloupce

### ISSUE THREAD

**Issue by tatyalien** [contributte/datagrid#212]
Ahoj,
v datatables je možnost si fixnout sloupce z leva i z prava. Bohužel v JS nejsem takový odborník, abych si to sám dopsal pro datagrid. příklad(https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html)

**Comment by paveljanda** [comment]
Maybe in some future PR. :)
