### ISSUE TITLE
Treeview - displaying all levels at once & remembering state 

### ISSUE THREAD

**Issue by jakubvojacek** [contributte/datagrid#234]
It would be nice if it would be possible to crate the whole tree-view with just one database query - instead of for children when node is opened the original query would return all this information. For example http://ublaboo.paveljanda.com/datagrid/tree-view in the example table you can get all levels by one query (`select * from ublaboo_category`). If the grid knew how to identify roots (callback returning `true/false` based on row value), the whole tree could be constructed.

When the whole tree would be loaded, the grid could remember its state (just like with filters) and upon refresh open all nodes that were opened before. Also a method could be to grid that would open all nodes by default (`$grid->openAllNodes(TRUE)`) and method to open specified nodes (`$grid->setDefaultOpenedNodes([1, 4, 10])`) - `1, 4, 10` would be keys specified by `$grid->setPrimaryKey()`

Do you think that this is something more people could use or is it just me?

Thanks!

**Comment by paveljanda** [comment]
I bet ... I know many people would use it!

But the thing is, Children are loaded via custom $.nette.ext javascript function (https://github.com/ublaboo/datagrid/blob/master/assets/dist/datagrid.js#L366-403). So it would be in my opinion difficult to keep the least changes in datagrid template.

Well, you can start some functionality in your fork and i will look at it. But i don't plan implementing that in oncoming weeks on my own (There are another issues (enhancements, questions, etc) I found more important).

**Comment by Bezdekm** [comment]
Is there any implementation in the new version of ublaboo dg?
