### ISSUE TITLE
Add alternative for Date range filter

### ISSUE THREAD

**Issue by misaon** [contributte/datagrid#285]
Ahoj,
chtěl jsem se tě zeptat, co by si říkal na **změnu způsobu filtrování** podle daterange?

Jde mi o následující: 
Momentálně funguje filtrování na způsobu dvou inputů (od/do) a na základě toho se vyfiltrují záznamy. Tahle cesta je určitě správná a jasná. 
Druhá alternativa ale je plugin [Date Range Picker](http://www.daterangepicker.com) (MIT). V tomto případě se dvě data "hodí" do jednoho inputu a následně se v PHP parsují dle separatoru. 
Výhoda této alternativy je mnohem lidštější přístup zvolením **již předefinovaných časových intervalů** (dnes, tento týden, minulý měsíc apod.). Také Bootstrap plugin plně podporuje a do tvé koncepce Datagridu se (dle mého) hodí mnohem více než stávající způsob filtrace. Další výhodou **je mnohokrát užší sloupec** (díky právě jednomu input filtru), momentálně mi přijde úplně zbytečně široký sloupec pro jednoduché datum.

Díky za zvážení.

**Comment by paveljanda** [comment]
Dobrý nápad. Dost škoda, že jsi s tím nepřišel dřív. :D

Zapřemýšlím nad tím, jaký průser by znamenala změna JS knihovny. Nebo jestli by to nešlo používat paraleleně se s távajícím řešením.

**Comment by misaon** [comment]
Díky :smile:

**Comment by jakubvojacek** [comment]
Novy datepicker vypada opravdu daleko lepe a prakticteji.

Kdyz uz se premysli nad vymenout datepickeru, bylo by mozne do datagridu pripsat vyber formatu, ve kterem se bude datum v datepickeru zobrazovat? Tedy napriklad m/d/y nebo d/m/y

Dik

**Comment by paveljanda** [comment]
@jakubvojacek Toho lze nyní docílit velice jednoduše, viz dokumentace: http://ublaboo.org/datagrid/filter#filter-date

**Comment by jakubvojacek** [comment]
@paveljanda Super, funguje, dik!

**Comment by misaon** [comment]
@paveljanda jen pro info, jak si daleko s implementací nového způsobu date range pickeru? 
Nenaléhám, jen se ptám :)

**Comment by paveljanda** [comment]
@misaon Neimplementoval jsem zatím nic nového v tomto směru. Nevím, zda na to přejít - to se mi nechce. Aktuální řešení je jednoduché a to se mi líbí. Nebo přidat další JS/CSS knihovnu a k tomu další formulářový prvek? Nebo přidat možnost registrovat v datagridu vlastní formulářové prvky?

Nevím, moc daleko jsem s tímto issue nedošel.

**Comment by misaon** [comment]
@paveljanda Možná se pro implementaci rozhodneme, protože tuto věc hojně využíváme.
Pokud tedy chceš, mohli bychom udělat i PR pro datagrid.

**Comment by paveljanda** [comment]
@misaon Zkusím vymyslet způsob, jak registrovat do DataGridu filtry třetích stran.

**Comment by misaon** [comment]
Progress? I like to help you with it.. 😊
