### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by igorpocta** [contributte/datagrid#416]
Add the render file for Bootstrap 4

**Comment by juniwalk** [comment]
Hello, I think it would be little premature. Bootstrap 4 has ben in alpha for over a year if I remember correctly. I would not hurry this up.

Ofcourse @paveljanda could have something else in mind.

**Comment by paveljanda** [comment]
@igorpocta Please reopen this issue when Bootstrap4 is stable.

**Comment by JanGalek** [comment]
beta now ;)

**Comment by martinvenus** [comment]
I think that beta2 is nearly stable. Could you please consider implementation?

**Comment by paveljanda** [comment]
@martinvenus Can you prepare a PR and send it to me when Bootstrap 4 is ready? :)
How much will be html structure and classes affected? Can we keep current template or is it necessary to create a new one for bs 4?

**Comment by radekdostal** [comment]
See https://forum.nette.org/cs/25444-ublaboo-datagrid-mocny-rychly-rozsiritelny-hezky-anglicky-dokumentovany-datagrid?p=22#p192059

**Comment by paveljanda** [comment]
@martinvenus @radekdostal Cool. So you know how to begin. :) There is probably necessary to keep more template files with more theme-specific CSS.

**Comment by paveljanda** [comment]
@igorpocta @JanGalek @martinvenus @radekdostal 
Bootstrap 4 support is in branch `bootstrap-4` (contains todays newest release `5.5.0`). THe only thing left is `bootstrap-select` for filter `MultiSelect` which is waiting for its author. As he says - it is already implemented and should be released soon (https://github.com/silviomoreto/bootstrap-select/issues/1135).

**Comment by caseyjhol** [comment]
Bootstrap 4 support has officially been added as a part of v1.13.0-beta, available here: https://github.com/snapappointments/bootstrap-select/releases/tag/v1.13.0-beta. Please post any issues in that repo from now on. Hoping for a quick beta.

**Comment by martinvenus** [comment]
@paveljanda bootstrap-select has been already released. Could you please merge bootstrap-4 branch to master? Thanks :)

**Comment by f3l1x** [comment]
Ping @paveljanda ;-)

**Comment by martinvenus** [comment]
Is there any progress pls? @jaroslavlibal mentioned that we are using this branch without any problem.

**Comment by martinvenus** [comment]
It seems that it takes more time to merge this branch to master. Could you please merge current master to this branch?

**Comment by f3l1x** [comment]
Bootstrap 4 is merged to v5.x.

https://github.com/contributte/datagrid/pull/700
https://github.com/contributte/datagrid/pull/699

**Comment by martinvenus** [comment]
It seems that there is some problem with updating v5.x-dev (https://packagist.org/packages/ublaboo/datagrid#v5.x-dev) on packagist. Last commit there is "e7cacbe" but should be "29915f0". Could you please check it?
