### ISSUE TITLE
Add a template for material design

### ISSUE THREAD

**Issue by Blizard** [contributte/datagrid#423]
Hi,

it could be fine to **choose a different type of template** for dataGrid. Now it supports only bootstrap version of template. 

There is a lot of design issues if I use the bootstrap template (default in dataGrid) in material design using [http://materializecss.com/](http://materializecss.com/).

**Comment by paveljanda** [comment]
Sure I would like to add more designs, but there are bigger priorities.

As always, we would welcome a pull-request! :)

**Comment by juniwalk** [comment]
@paveljanda There are also some problems with keeping those designs up-to-date, as we talked about. :)

**Comment by misaon** [comment]
Pavel, can you make some methods for create thirds design? I like to create some templates for Foundation framework, materialize, Metronic etc. I will send PR.

**Comment by paveljanda** [comment]
@misaon As for now, simply creating new datagrid.css styles should cover many desing themes. RIght? For example: datagrid.materialize.css, datagrid.metronic.css etc.

**Comment by misaon** [comment]
Materialize have own css styles, its a CSS framework. You need include css into html head and change table class names etc. We need edit latte files.

**Comment by paveljanda** [comment]
@misaon Any idea about using different classes and same layout?

**Comment by misaon** [comment]
hm, what about different latte templates?

**Comment by f3l1x** [comment]
Closing it due to inactivity. Thanks. 🎉
