### ISSUE TITLE
Reset filter button shown when default filter set & in default state

### ISSUE THREAD

**Issue by pavelgajdos** [contributte/datagrid#453]
Let's have a select filter 'status' with the following options:

null or '' => 'All'
1 => 'Active'
0 => 'Inactive'

Without a default filter set, the reset button is shown only when 1 or 0 is selected in the filter. That's an expected behaviour. 

Setting a default filter to ['status' => 1] causes a state when the reset button is shown for value 1 (the same applies to value 0), but not for null. 

I would expect the reset button is shown for null and 0, and not for 1 as this is the default filter value.

I might be able to send a pull request , but I'd like to know first if you consider this a bug or a feature.

Thank you.

**Comment by paveljanda** [comment]
Hm, that is hard to say. Reset filter button basically triggers a session flush, but does not expect any values in default filter.

@pavelgajdos What behaviour would you suggest?
