### ISSUE TITLE
Support NittroJS

### ISSUE THREAD

**Issue by romanmatyus** [contributte/datagrid#473]
Add support for [NitroJS](https://github.com/nittro/nittro).

**Comment by paveljanda** [comment]
@romanmatyus Will you? :)
I am not using it. Although I would love to support Nittro, I have no knoweladge of it and I won't be using it following couple of months.

**Comment by romanmatyus** [comment]
Now it's just an idea. I too do not have knowledge. Yet ..
I will try implement support within programing new project.

**Comment by paveljanda** [comment]
@romanmatyus Perfect.

**Comment by paveljanda** [comment]
Maybe in future? :)

**Comment by romanmatyus** [comment]
@paveljanda Maybe in next life, not enough time :/
