### ISSUE TITLE
Support datasource ArrayCollection from Nextras/ORM

### ISSUE THREAD

**Issue by honzarac** [contributte/datagrid#508]
When I use custom sql query in NextrasORM and set result as datasource, datatgrid try call getQueryBuilder on ArrayCollection and it throws:

Nextras\Orm\MemberAccessException
Call to undefined method Nextras\Orm\Collection\ArrayCollection::getQueryBuilder().

**Comment by paveljanda** [comment]
@honzarac I don't really use Nextras ORM. Can you send a PR with your solution?
