### ISSUE TITLE
Small inline edit input type color

### ISSUE THREAD

**Issue by JanGalek** [contributte/datagrid#539]
Hi,
when I use 
```
$grid->addColumnText('color', 'Barva')
        ->setEditableInputType('color', ['style' => 'width: 100%'])
        ->setEditableCallback(function ($id, $value) {
            $this->rubricTypesRepository->updateSingle($id, 'color', $value);
            $this['typesGrid']->redrawControl();
        })
        ->setAlign('center')
        ->setSortable();
```
and click to edit color, then it send and after browser open color palete, and when I select color it dont change it. 

Do I something wrong or it's normal ? 
How you solve it ?

Thanks

**Comment by paveljanda** [comment]
Hmm, the submit behaviour would have to be actualy changed in datagrid.coffee..

Can you do it? :)

**Comment by JanGalek** [comment]
I will look at it ;)
