### ISSUE TITLE
TLD as persist

### ISSUE THREAD

**Issue by JanGalek** [contributte/datagrid#546]
Good morning,
I have created translating page by TLD like:

```
$router[] = new Route('//www.%sld%.<locale cz|sk>', 'Homepage:default');
```

and presenter 
```
abstract class BasePresenter extends Presenter
{
    /** @persistent */
    public $locale;
    ...
}
```
so when I go to page with datagrid, it add parameter locale to url, but parameter locale is tld, so then I see url like
`http://www.localweb.cz/administrace/akcni-nabidky/default?locale=cz&typesGrid-per_page=10`

this is` not a bug, but not look nice :) Or do you have some solution how to solve it ?

Thank you

**Comment by paveljanda** [comment]
@JanGalek I see. Hmm. Can you send me a sandbox-like zip where I could play around with this situation? Thanks. :)

**Comment by JanGalek** [comment]
@paveljanda ok, I have ready sandbox zip, where I have upload for you ?

**Comment by paveljanda** [comment]
@JanGalek RIght here, if it is not a problem for you. :)

**Comment by JanGalek** [comment]
[datagrid-tld.zip](https://github.com/ublaboo/datagrid/files/1149679/datagrid-tld.zip)

I dont know, than on github can upload files, thanks for info 👍
