### ISSUE TITLE
Bower is DEAD, welcome NPM.

### ISSUE THREAD

**Issue by misaon** [contributte/datagrid#550]
Can you do this? Thanks a lot.

**Comment by petrparolek** [comment]
why is bower dead? I dont think so!

**Comment by paveljanda** [comment]
It is not dead but there should exist a npm package. I will add it.

**Comment by paveljanda** [comment]
@misaon Can you please test it? I am not really a frontend developer, know just a little bit about npm.
Should I update the version in `package.json` each time a make some changes to assets?

**Comment by paveljanda** [comment]
@misaon ping :)

**Comment by paveljanda** [comment]
@misaon pong

**Comment by jahudka** [comment]
@paveljanda yes, NPM doesn't follow the git repo like Bower and Composer do, so each time you release a new version you must update the version string in `package.json` and issue a `npm publish` command. It can easily be automated as part of a CI pipeline though - there's a handy NPM command called `npm version <major|minor|patch>`, which, when issued in a project directory with a clean working tree, updates the version in `package.json` accordingly _and_ creates a new git tag; you can then use that to create releases and just have a simple CI build triggered by tags pushed to the github repo that then issues `npm publish` for the new tags. Even better, you can attach hooks to the `npm version` command being run - with those you can e.g. compile assets _before_ the new tag is created - which means you'll never forget to do it before publishing a release.

**Comment by paveljanda** [comment]
@jahudka Thanks for explaining to me. I will look more deeply in the CI in following days. Appreciate that!

**Comment by martinknor** [comment]
@paveljanda there is problem with dependencies, actual package hasn't dependencies like bower...
Can you fix it?
```
"jquery": ">= 1.11.0 <3.0",
    "happy": ">= 1.0.0",
    "bootstrap-datepicker": ">= 1.6.0",
    "nette-forms": "^2.3",
    "nette.ajax.js": ">= 2.1.0",
    "jquery-ui-sortable": "https://github.com/ryantbrown/jquery-ui-sortable.git",
    "bootstrap": ">= 3.3.0"
```

**Comment by f3l1x** [comment]
NPM package works. Closing it.
