### ISSUE TITLE
Font Awesome 5 Support

### ISSUE THREAD

**Issue by brkos** [contributte/datagrid#618]
Add the render file for Font Awesome 5

**Comment by pitr82** [comment]
Hi @paveljanda , @f3l1x 
When can I expected support for Font Awasome 5 ? 
Now we use only version 5 PRO.

**Comment by f3l1x** [comment]
Well, from my point of view, I don't know. I have to tried to use FA 5 and it was hell for me. Maybe I was doing something wrong, but until now I use FA 4. 

Would you be able to prepare PR with FA?
