### ISSUE TITLE
Enable horizontal scroll when the DataGrid is too wide

### ISSUE THREAD

**Issue by maraerben** [contributte/datagrid#619]
it would be so nice to enable horizontal scroll, when the DataGrid is wider than the whole page. Now, when my table has many columns I can not see all of them. (On screenshot there are another two columns off the screen)

<img width="1347" alt="snimek obrazovky 2018-02-26 v 19 23 50" src="https://user-images.githubusercontent.com/17090177/36687873-0e42345a-1b2b-11e8-8203-44f563f550aa.png">

**Comment by paveljanda** [comment]
@maraerben You can send a PR. :)
I would also consider the hidden columns feature.
