### ISSUE TITLE
MultiSelect filter is not working with nextras/orm

### ISSUE THREAD

**Issue by matrixinfologics** [contributte/datagrid#623]
I am trying to using multiselect filter with nextras/orm relative data. Its not working and return the error like
`Unknown column 'tags.id' in 'where clause`

Filter code
`$grid->addFilterMultiSelect('tags', 'Tags:', $this->tagManager->findAll()->fetchPairs('id', 'name'), 'tags.id');`

Simple Select filter is working with it. Please provide some solution regarding that.

**Comment by paveljanda** [comment]
@matrixinfologics I am not really using Nextras ORM, but you can send a PR. :)
