### ISSUE TITLE
Treeview and Bootstrap 4

### ISSUE THREAD

**Issue by rkor11** [contributte/datagrid#624]
In Bootstrap 4 has been removed .hidden class. So in treeview, there is shown link/arrow to children view for every item. It could be replaced by .d-none class.

**Comment by paveljanda** [comment]
@rkor11 Can you send a PR, please? :)

**Comment by rkor11** [comment]
As I can see, you have already fixed it by adding .hidden class in datagrid.scss to bootstrap-4 branch. But I can send PR with modified datagrid_tree.latte for compatibilty with bootstrap 3&4, if you can

**Comment by paveljanda** [comment]
This bug is fixed in the bootstrap-4 branch as you mentioned.
