### ISSUE TITLE
[6.0] Class DibiFluent  has been renamed to Dibi\Fluent.

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#625]
Hello, could you please replace old DibiFluent with Dibi\Fluent?

`Argument 1 passed to Ublaboo\DataGrid\DataSource\DibiFluentDataSource::__construct() must be an instance of DibiFluent, instance of Dibi\Fluent given`

DibiFluent in Dibi does not exist anymore.

Thank you very much.

**Comment by BigOHenry** [comment]
I made pull request already for this

**Comment by cniry** [comment]
+1

**Comment by rumcais** [comment]
+1

**Comment by f3l1x** [comment]
It's a part of this PR. 

https://github.com/ublaboo/datagrid/pull/648

**Comment by f3l1x** [comment]
Please, test it again according to master branch.

**Comment by BigOHenry** [comment]
Its working for some time already :-) Thank you!

**Comment by f3l1x** [comment]
Thanks.
