### ISSUE TITLE
Use higher version of ublaboo/responses

### ISSUE THREAD

**Issue by f3l1x** [contributte/datagrid#632]
I'm not sure if it's in correct form.

```
"ublaboo/responses": "~1.0.0|~2.0.0",
```

According to composer docs (https://getcomposer.org/doc/articles/versions.md#version-range) it should be in this form.

```
"ublaboo/responses": "~1.0.0 || ~2.0.0",
```

WDYT @paveljanda?

**Comment by paveljanda** [comment]
@f3l1x It should be possible (https://semver.mwl.be/#?package=ublaboo%2Fresponses&version=~1.0.0%7C~2.0.0&minimum-stability=stable). But you're right, `||` is documented so we should use that one.

**Comment by f3l1x** [comment]
It's strange behaviour. :-)

`composer outdated` still reports we're using ~1.0.0, but I don't know why. 

PS: Yep, I'm using ublaboo datagrid. Shame on me... :-D

**Comment by f3l1x** [comment]
This is solved by other package. ublaboo/responses will be dropped since v6.0.0.
