### ISSUE TITLE
Cannot set custom Paginator template

### ISSUE THREAD

**Issue by mhucik** [contributte/datagrid#635]
Hi,
I wanted to set custom Paginator template. But AFAIK Its posible to do it only after datagrid is connected to PresenterComponent, but I want to do it before that happens. 
I would like to make some general factory class, which would accept my design requirements for grid.

I also made some changes, which allows me to do that here: https://github.com/ublaboo/datagrid/pull/634

Thanks for amazing grid :)

**Comment by paveljanda** [comment]
#634 was merged. :)
