### ISSUE TITLE
Nette\ComponentModel\Component::__construct() argument $parent is deprecated, use $parent->addComponent() instead.

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#638]
With new nette utils getting this error:
`Nette\ComponentModel\Component::__construct() argument $parent is deprecated, use $parent->addComponent() instead.  `

in this row:
`$grid = new DataGrid($this, $name);`

**Comment by petrparolek** [comment]
you have to use:
`
$grid = new DataGrid();
$this->addComponent($grid, $name);
`

**Comment by BigOHenry** [comment]
Thank you! Its working.

**Comment by f3l1x** [comment]
I think it's already fixed in v5.x branch and all problem resolved. Closing for now.
