### ISSUE TITLE
[6.x] roadmap

### ISSUE THREAD

**Issue by f3l1x** [contributte/datagrid#669]
We should set some expectation on future development.

I must say, there will be BC breaks, it sure. But don't worry, we will try to make it more pleasant.

Changes:
- Nette >=3.0 only
- PHP >=7.3 only
- change namespace Ublaboo -> Contributte
- transfer dynamic doc on Github docs (to display it on https://contributte.org)
- apply contributte's codestyle 
- apply phpstan
- rewrite completely tests
- merge datasources into single repository
  - https://github.com/contributte/datagrid-nette-database-data-source (>=3.0) [#748] 
  - https://github.com/contributte/datagrid-leanmapper-data-source (>=3.3) [#751]
  - https://github.com/contributte/datagrid-elasticsearch-data-source [#928]
  - https://github.com/contributte/datagrid-dibi-data-source (>=4.0) [#749] 
  - https://github.com/contributte/datagrid-doctrine-data-source (>=2.6) [#750] 
  - https://github.com/contributte/datagrid-nextras-data-source (>=3.0) [#752]
- refactoring
  - rename snake_case to camelCase

**Comment by martingold** [comment]
Awesome!.. Could you tag existing issues and create new ones describing what you need help with towards reaching v6?

**Comment by f3l1x** [comment]
@martingold I will try to ;-)

**Comment by f3l1x** [comment]
@martingold Better? :-)

**Comment by dakorpar** [comment]
I would really love it if tests are in phpunit which is far better supported. nette tester plugin for phpstorm is crashed for few months already...

**Comment by paveljanda** [comment]
@dakorpar nette/tester can be simply ran using command line interface. :) I would stick to nette/tester because of its simplicity.

**Comment by dakorpar** [comment]
@paveljanda sure you can, but having codecoverage directly in IDE is big plus plus right click and debugging selected test method is huge advantage and thats not possible woth nette tester... :)

**Comment by f3l1x** [comment]
Resolved, v7.0.0 roadmap here #1025
