### ISSUE TITLE
ColumnsSummary->setPositionTop()

### ISSUE THREAD

**Issue by romanmatyus** [contributte/datagrid#673]
Please, it's a chance that it will be merged PR for this feature?

```php
$datagrid->setColumnsSummary()
	->setPositionTop(); // Or take it down again: ::setPositionTop(FALSE)
```

Thanks

**Comment by paveljanda** [comment]
@romanmatyus Is there any PR for that feature?

**Comment by romanmatyus** [comment]
@paveljanda No, the question is whether it makes sense to do it :)

**Comment by paveljanda** [comment]
I guess it does. What do you think @f3l1x?

**Comment by f3l1x** [comment]
I like it. PR is welcomed ;-)

**Comment by vladimirbiro** [comment]
$datagrid->setColumnsSummary()->setPositionTop() is ready in PR :)

**Comment by romanmatyus** [comment]
Closed with https://github.com/contributte/datagrid/pull/682.

Thx for merge
