### ISSUE TITLE
Bump v5.7.0

### ISSUE THREAD

**Issue by f3l1x** [contributte/datagrid#680]
I would like to prepare v5.7.0.

Including:
- bootstrap 4 branch [#416]
- NPM enhancement [#676]

Any other ideas? Please consider we're moving to PHP 7.1 in v6.x, thus, no big feature requests please.

cc @paveljanda

**Comment by f3l1x** [comment]
I think we can release v5.7.0? @paveljanda and others?

**Comment by paveljanda** [comment]
@f3l1x Yes, let's do it.

**Comment by f3l1x** [comment]
Done
