### ISSUE TITLE
Cached filters in cookies

### ISSUE THREAD

**Issue by haelexuis** [contributte/datagrid#691]
Hello, could you please check if filter still exits in PHP? I deleted 1 column from table and code, but apparently, I filtered that column before, and it remained in my browser cookie cache, you know what I mean.

Ublaboo\DataGrid\Exception\DataGridFilterNotFoundException: Session filter: Filter [description] not found

**Comment by paveljanda** [comment]
@haelexuis `DataGrid::setStrictSessionFilterValues()` :)
