### ISSUE TITLE
Horizontal and vertical grid scrolling 

### ISSUE THREAD

**Issue by janmottl** [contributte/datagrid#729]
Customer requires:
- horizontal and vertical grid scrolling 
- table header should be fixed on vertical scrolling
- paging, group actions and setting should not move on horizontal scrolling

The best would be if this functionality would part of datagrid. 

My customer insisted on this functionality so I had to impelement it. It's a JavaScript function.
It would be easier to implement it directly in grid. Perhaps the authors are inspiring :)

You can find it here https://github.com/janmottl/datagrid.scroll

**Comment by paveljanda** [comment]
Thanks a lot for the example but I am not going to support this feature for now. Sorry.
May I suggest columns hiding for similar requests?

**Comment by janmottl** [comment]
Column hiding is already used at customer. It would be appreciated if user could change column order.
