### ISSUE TITLE
UUID support in addAction (signal)

### ISSUE THREAD

**Issue by rixafy** [contributte/datagrid#735]
Hi, recently I tried make Edit button in datagrid, datagrid is in component which is attached to presenter.
I created handleEdit($id) in component for handling signal, but when I use link 'edit!' and parameters ['id' =>'id'], 'id' patameter does not appear in the link. I suppose the problem is that $item['id'] is Uuid object, not string or integer, so you need to cast it to string by calling toString().

This is my workaround

![image](https://user-images.githubusercontent.com/45132928/51356455-e3d2e800-1aba-11e9-9104-7b08fe39499e.png)

![image](https://user-images.githubusercontent.com/45132928/51356392-abcba500-1aba-11e9-9b45-11990c49a8e6.png)

Suggested solution:
https://github.com/contributte/datagrid/blob/v5.x/src/Row.php#L90
is_array($this->item) is true, because I have array result of selected fields, but in my array result, $item['id'] is Uuid entity, https://snipcode.link/7Mv for instance

**Comment by paveljanda** [comment]
@rixafy You can send a PR with uuid support. :) (Most people use `ramsey/uuid`?)

**Comment by JakubKontra** [comment]
@paveljanda  ramsey/uuid +1

**Comment by rixafy** [comment]
@JakubKontra, what isn't supported exept this (it works well, but only when the href and parameters aren't used in action, and it's handled by router <id>)? Maybe I can look at it, but I'm using this datagrid with UUIDs maybe month and I had only this issue.

**Comment by rixafy** [comment]
Fixed in https://github.com/contributte/datagrid/pull/736
