### ISSUE TITLE
Naja support

### ISSUE THREAD

**Issue by dakorpar** [contributte/datagrid#738]
I would actually go with it also, but coffe script is kinda problematic, any issue to code this in js?
Anyone has this working already?

**Comment by paveljanda** [comment]
There is no problem of doing it in JS. :)

**Comment by dakorpar** [comment]
what about removing coffe script for existing part as well and rewrite this so it automatically detects naja/nette.ajax.js and so that we don't have duplicated code in two libs?

**Comment by paveljanda** [comment]
Datagrid is already able to use Naja
