### ISSUE TITLE
BS 4 chybné zobrazení multiselect box v filtru

### ISSUE THREAD

**Issue by petrparolek** [contributte/datagrid#742]
ahoj, mohl by někdo prosím opravit bug v css? Když použiju Bootstrap 4.2 s https://github.com/snapappointments/bootstrap-select/tree/v1.13.5 , tak se špatně zobrazuje select box 

![screenshot_2019-02-22 nette sandbox](https://user-images.githubusercontent.com/6066243/53301161-8bc49980-384f-11e9-896c-6d483c0684ab.png)

Takhle select box má vypadat:
![screenshot_2019-02-22 nette sandbox 2](https://user-images.githubusercontent.com/6066243/53301160-8bc49980-384f-11e9-9e25-53feb36063e2.png)

**Comment by dakorpar** [comment]
English please?

**Comment by petrparolek** [comment]
@dakorpar In English for you - could anybody fix a bug in CSS please? When I use Bootstrap 4.2 with Bootstrap-select 1.13.5, select box is shown worong

**Comment by petrparolek** [comment]
ping @paveljanda  @f3l1x

**Comment by f3l1x** [comment]
pong

**Comment by paveljanda** [comment]
@petrparolek I am not using BS4 anywhere so can you please send some PR with css fix? Thank you. :)

**Comment by petrparolek** [comment]
Ok, I can try it

**Comment by paveljanda** [comment]
BS4 selects should be fixed in v6
