### ISSUE TITLE
DoctrineDataSource - Chyba při HIDDEN ORDER BY

### ISSUE THREAD

**Issue by JKoty** [contributte/datagrid#743]
`
$qb->addSelect('CASE WHEN entity.assignedAt IS NULL THEN 2 ELSE 1 END AS HIDDEN priority');
$qb->addOrderBy('priority', 'DESC');
$grid->setDataSource($qb);
`
vyhodí část se selectem v `getCount()` při získávání počtu, což způsobí query exception kvůli chybějícímu parametru `priority`.

**Comment by JKoty** [comment]
Přidání `$data_source->resetDQLPart('orderBy');` do `getCount()` to řeší. Jelikož je tam data source naklonovaný, nemělo by to mít neočekávané důsledky.

```
// DoctrineDataSource.php, line 108
/**
	 * Get count of data
	 * @return int
	 */
	public function getCount()
	{
		if ($this->usePaginator()) {
			return (new Paginator($this->getQuery()))->count();
		}
		$data_source = clone $this->data_source;
		$data_source->select(sprintf('COUNT(%s)', $this->checkAliases($this->primary_key)));
		$data_source->resetDQLPart('orderBy');

		return (int) $data_source->getQuery()->getSingleScalarResult();
	}
```

Nenašel jsem, jak se přispívá do Contributte a nemám s tím zkušenost. Když mi to někdo vysvětlí, tak to příště budu moci přidat nějak korektněji :)

**Comment by paveljanda** [comment]
@JKoty Díky, super. Zkusil jsem na základě tvého issue udělat Pull Request: https://github.com/contributte/datagrid/pull/744

Můžeš si ho zkusit udělat taky podle návodů (https://www.youtube.com/watch?v=rgbCcBNZcdQ) a my ho pak mergnem. Tak řekni, jestli do toho chceš jít, ať máš taky nějaký příspěvek v Contributte. :)
Pokud ne, mergnem ten, co jsem poslal. :)

**Comment by JKoty** [comment]
Dík za návod, hned zítra to zkusím ;)

**Comment by JKoty** [comment]
No jasně, nenapadlo mě, že si musím repozitář nejdřív forknout, místo abych ho klonoval.
Tady. Dík :)
#745
