### ISSUE TITLE
InlineAdd vs Filter - validationscope

### ISSUE THREAD

**Issue by jiriermis** [contributte/datagrid#762]
Hi
I use inlineAdd/inlineEdit where inputs are setRequired. I have also filters. When typing text to a filter, it shows a message that inputs from inlineAdd/inlineEdit  are mandatory and the filter doesn't work. If I open inlineAdd and immeditelly close it by button cancel, then the filter works properly, until I hit reset filter button.

Please help to fix the issue. It is know long time. I saw same issue was fixed 2 years ago by addind validation scope, but the issue still exists.
Test sandbox create by user from nette forum here: https://github.com/petrparolek/datagrid-filters-sandbox

Thank you

**Comment by paveljanda** [comment]
Fixed in upcoming version 6 :)

https://github.com/contributte/datagrid/commit/5e8db96fa74606b8f34b31e90ae867d113e60431
