### ISSUE TITLE
Please provide an instance of Ublaboo\DataGrid\DataSource\IDataSource or an array search

### ISSUE THREAD

**Issue by genesiscz** [contributte/datagrid#766]
This if statement breaks old code where I was used to `$this->setDataSource($netteDatabaseSelection)`.

https://github.com/contributte/datagrid/blob/a328e35b96885517a616b2d86bdb98378831dae1/src/DataGrid.php#L504

Using 6.0 version

**Comment by paveljanda** [comment]
:D Aaaa there is no 6.0 version yet.

IOn 6.0, there **will be** BC breaks. But this one will not break backward compatibility - see https://github.com/contributte/datagrid/blob/v6.x/src/DataGrid.php#L502

**Comment by genesiscz** [comment]
Oh, okay. Anyway, I tried to `composer require ublaboo/datagrid:~5.8` to make it work again with Nette v3 but in fails on 
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: nette/application[v2.4.x-dev, 3.0.x-dev].
    - Can only install one of: nette/application[v2.4.x-dev, 3.0.x-dev].
    - Can only install one of: nette/application[v2.4.x-dev, 3.0.x-dev].
    - ublaboo/datagrid v5.x-dev requires nette/application ^2.4.0 -> satisfiable by nette/application[v2.4.x-dev].
    - Installation request for ublaboo/datagrid ~5.8 -> satisfiable by ublaboo/datagrid[v5.x-dev].
    - Installation request for nette/application (locked at 3.0.x-dev, required as ~3.0) -> satisfiable by nette/application[3.0.x-dev].


Installation failed, reverting ./composer.json to its original content.
``` 

How am I supposed to install Ublaboo on Nette3 right now?

**Comment by paveljanda** [comment]
It is not possible yet. We were waiting for other packages to  migrate to nette 3.0.  We are currently working on the 6.0 version. It will be here soon. :)

**Comment by paveljanda** [comment]
But if the datagrid works for you in branch `v6.x`, it is a great news! I did not test it yet - I am only refactoring and fixing phpstan bugs..

**Comment by genesiscz** [comment]
It doesn't :)

**Comment by paveljanda** [comment]
What does that mean? Do you have some detailed answer?

**Comment by genesiscz** [comment]
Hmm I wanted to post an answer with lines pointing to github files, but got confused instead. If I am having composer pointing to ^6.0 version and in composer.lock I see it's v6.x-dev, which branch am I currently using then? It shows me that I have an error on this line: 
`1022:         return $this->actions[$key] = new Action($this, $href, $name, $params);`
but when I look this line up on this repo, I can't seem to find the line at all. In the 6.x branch it is on line https://github.com/contributte/datagrid/blob/v6.x/src/DataGrid.php#L911

**Comment by genesiscz** [comment]
Oh I had some terrible mix of versions installed or something I guess, I deleted the package entirelly, reinstalled, deleted the if statement in DataGrid.php and now I am getting deprecation errors like 
`Nette\Utils\Callback::invokeArgs() is deprecated, use native invoking` right here

https://github.com/contributte/datagrid/blob/82c8df4d474bb0b746629abc24f547e769d18839/src/DataGrid.php#L395

Guess I just have to wait or try to fix it on my own for now. Thanks for help :-)

**Comment by genesiscz** [comment]
> :D Aaaa there is no 6.0 version yet.
> 
> IOn 6.0, there **will be** BC breaks. But this one will not break backward compatibility - see https://github.com/contributte/datagrid/blob/v6.x/src/DataGrid.php#L502

By the way you said this one won't be a BC break. How come it's not a BC break? I didn't get the hint from link you posted. What am I missing? Passing a simple Nette\Database\Table\Selection gives the InvalidArgumentException, which wasn't happening few versions earlier.

**Comment by paveljanda** [comment]
I will fix the `invokeArgs` bug today.
You had some old commit. Current HEAD of `v6.x` branch should not show you the files you were point to.
