### ISSUE TITLE
Filter on `ArrayDataSource` is value is `null`

### ISSUE THREAD

**Issue by patrickkusebauch** [contributte/datagrid#781]
**Error message:**
TypeError
Argument 1 passed to Nette\Utils\Strings::toAscii() must be of the type string, null given, called in /var/www/vendor/ublaboo/datagrid/src/DataSource/ArrayDataSource.php on line 149

**Datagrid version:** v6.x-dev

**Steps to reproduce**
1. Create a datagrid with ArrayDataSource, where one of the row values is `null`.
2. Try to filter over this value with `->setFilterSelect("all other options except null")->setPrompt('All')`

**Comment by kuchy** [comment]
Datagrid version: v6.2.3

Had similar issue. 

has filter: 
`$grid->addFilterText('id', 'id');`
if you enter number `123`

gets: 
`TypeError: Argument 1 passed to Nette\Utils\Strings::toAscii() must be of the type string, int given, called in ....`

I suggest to cast it...sending PR

**Comment by paveljanda** [comment]
closed via #846
