### ISSUE TITLE
Documentation? Column link external link

### ISSUE THREAD

**Issue by patrickkusebauch** [contributte/datagrid#783]
Maybe this is not possible, but I am trying to add a link to an external site.

I was hoping to use ColumnLink.

I am sure, I can do it with ColumnText and a custom render function, but is this also possible with ColumnLink?

**Comment by BigOHenry** [comment]
Nope, only way what i know is custom render.

**Comment by petrparolek** [comment]
or you can do redirect on presenter action

**Comment by f3l1x** [comment]
Cc @paveljanda. Don’t we really support these links?

**Comment by paveljanda** [comment]
No it is not possible right nos.
