### ISSUE TITLE
Datetime column - error when value is null

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#790]
![datagrid-date](https://user-images.githubusercontent.com/15823552/58426090-dd253480-809b-11e9-8f96-baec445678e2.png)

**Comment by paveljanda** [comment]
Thank you! It if fixed in `master`: https://github.com/contributte/datagrid/commit/6e52a5afabd48d20f6d72049f4998b90bd8b0ba2

**Comment by BigOHenry** [comment]
Working. Thank you!
