### ISSUE TITLE
Reversed logic in setHeaderEscaping.

### ISSUE THREAD

**Issue by kuchy** [contributte/datagrid#792]
By function doc it means: 
`Should be column header escaped in latte?`
and real logic act reversed:
`->setHeaderEscaping(true)`
will turn **off** escaping of header name (turn on ussage of noescape) and
`->setHeaderEscaping(false)`
will turn **on** escaping of header name in template.
It's bug or feature?

**Comment by paveljanda** [comment]
Uups that is probably a bug. I will fix it. Thanks.
