### ISSUE TITLE
paginator option 'All' does not work - v5.7.2

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#795]
Hello, i have problem with paginator when is selected All option. Page is refreshed, but displayed values are from first option of Paginator (default 10).

Using latest Nette 2.4 and Dibi 4. Data source is Dibi Fluent. 

I found problem in method `getPerPage` at class ` \Ublaboo\DataGrid\DataGrid`:
```
public function getPerPage()
	{
		$items_per_page_list = $this->getItemsPerPageList();
		$per_page = $this->per_page ?: reset($items_per_page_list);

		if (($per_page !== 'all' && !in_array((int) $this->per_page, $items_per_page_list, true)) // there should be array_keys($items_per_page_list)
			|| ($per_page === 'all' && !in_array($this->per_page, $items_per_page_list, true))) { // there should be array_keys($items_per_page_list)
			$per_page = reset($items_per_page_list);
		} 
		return $per_page;
	}
```

Thank you!
EDIT: 
Problem is when values are translated. The condition looking into values (instead of keys) and searching 'all', but there isnt one. 
![image](https://user-images.githubusercontent.com/15823552/58881431-7971bb80-86da-11e9-812a-345cc5862584.png)

**Comment by BigOHenry** [comment]
I closed the PR because i need glasses (more info there). Could you make 5.x release with the fix please?

Thank you!

**Comment by paveljanda** [comment]
It should be already fixed: https://github.com/contributte/datagrid/blob/v5.x/src/DataGrid.php#L2782

**Comment by Sikipiki** [comment]
No, it is not fixed. In v5.7.5 is still this issue.
Problem is with array_key_exists(). There must be in_array().

Variable $items_per_page_list looks like this:
0 => 10
1 => 20
2 => 50
3 => "all"
Even if it is then translated into e.g Czech.

Right condition:
`if (($per_page !== 'all' && !in_array((int) $this->per_page, $items_per_page_list, true))
	|| ($per_page === 'all' && !in_array($this->per_page, $items_per_page_list, true))) 
{
	$per_page = reset($items_per_page_list);
}`

Pleas fix it in the new version e.g v5.7.6.
