### ISSUE TITLE
StatusColumn doesn't work

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#803]
Hello,
i have this array for column status:
![image](https://user-images.githubusercontent.com/15823552/59906537-3cf7cc80-9409-11e9-8b5b-95f9acc50d79.png)

Result in datagrid:
![image](https://user-images.githubusercontent.com/15823552/59906620-7a5c5a00-9409-11e9-8b39-c27651af9d28.png)

Problem is method `getCurrentOption` in `Ublaboo\DataGrid\Column\ColumnStatus` class:
```
        /**
	 * Find selected option for current item/row
	 */
	public function getCurrentOption(Row $row): ?Option
	{
		foreach ($this->getOptions() as $option) {
           // bdump($option->getValue());
           // bdump($row->getValue($this->getColumn()));
           // bdump('--------');
			if ($option->getValue() === $row->getValue($this->getColumn())) {
				return $option;
			}
		}

		return null;
	}

```
There is a dump:
![image](https://user-images.githubusercontent.com/15823552/59906732-b4c5f700-9409-11e9-8525-29d110545044.png)

Possible fix:
**1)** 
```
if ($option->getValue() == $row->getValue($this->getColumn())) {
	return $option;
}
```
OR
**2)**
```
if (strval($option->getValue()) === strval($row->getValue($this->getColumn()))) {
	return $option;
}
```
OR 
**3)** 
`$option->getValue()` should return string

**Comment by BigOHenry** [comment]
I made PR for option **2)**

**Comment by BigOHenry** [comment]
What is status about this issue? Maybe better solution would be option 2 or 3.

**Comment by BigOHenry** [comment]
I made fix for this in #827, old communication is at #804.

**Comment by BigOHenry** [comment]
Any motivation fixing this? I made PR #827 almost year ago with no reaction. Thank you

**Comment by paveljanda** [comment]
I will look into it later this day

**Comment by paveljanda** [comment]
It is likely caused by your database driver, with dibi, it works fine.

What database driver are you using?

When your driver displays `"1"` for `1`, please set the options using:

```php
->setOptions([
	'4' => 'Plánovaná',
	'5' => 'Dokončená',
	'6' => 'Zrušená',
]);
```

**Comment by BigOHenry** [comment]
Thank you.
I am using dibi too. This is not exact problem. I will send more info
tomorow.

Dne st 24. 6. 2020 16:12 uživatel Pavel Janda <notifications@github.com>
napsal:

**Comment by paveljanda** [comment]
Could you please create sandbox.like repository where I can see this behaviour? Maybe it can be cloned from https://github.com/planette/playground/tree/master/contributte-datagrid

**Comment by BigOHenry** [comment]
Hello, sorry for delay, i was busy. I made quick datagrid example here: https://github.com/BigOHenry/sandbox

Database script is in resources/test.sql

There are always 2 (setOptions vs addOption) column per data type (int, string, bool, bool string) and 3 rows with values (1/true, 0/false, null/false) and all columns are ColumnStatus with multi select filters.

The result is some columns doesnt has status dropdown and some filters doesnt work. Methods setOptions and addOption with filter on same values leads to different results.
 
Thank you very much
