### ISSUE TITLE
Value '0' is out of allowed set [10, 20, 30, 50, 100] in field 'per_page'.

### ISSUE THREAD

**Issue by aleswita** [contributte/datagrid#814]
After upgrade to **v5.7.4**, datagrid throws an exception, after change the items per page:
```
Value '0' is out of allowed set [10, 20, 30, 50, 100] in field 'per_page'.
```

```php
$grid = new Ublaboo\DataGrid\DataGrid();

$grid->setTranslator($this->translator);

$grid->setStrictSessionFilterValues(false);

$grid->setItemsPerPageList([10, 20, 30, 50, 100], false);
...
```

**Comment by radekdostal** [comment]
I agree. After clearing session only one record is shown.

**Comment by paveljanda** [comment]
I will have a look at it

**Comment by paveljanda** [comment]
Please downgrade your version. Tag `5.7.4` was not intended to happen.

**Comment by radekdostal** [comment]
BTW v5.7.3 requires Nette 3.

**Comment by paveljanda** [comment]
`5.7.3` was also deleted. No idea how it made its way into this repository. GitHub merges also tags from foreign branches when merging pull-requests??
