### ISSUE TITLE
Aggregate function row is never shown

### ISSUE THREAD

**Issue by elring** [contributte/datagrid#831]
When I add some aggregate function via addAggregationFunction, the row with results is never shown.

Template is missing something like:
`{if (($control->hasSomeAggregationFunction()) || ($columnsSummary) && !$columnsSummary->getPositionTop())}` what used to be there.

**Comment by paveljanda** [comment]
Fixed in #870

**Comment by paveljanda** [comment]
https://github.com/contributte/datagrid/releases/tag/v6.2.8
https://github.com/contributte/datagrid/blob/master/.docs/columns.md#aggregation-function
