### ISSUE TITLE
Fix paginator when using translated 'all' option

### ISSUE THREAD

**Issue by mczudek00** [contributte/datagrid#833]
Hi,

I found an issue when using translated 'all' option in items.

This code is searching for 'all' in values, but the value contains translated 'all' option so it resets the $per_page value.

```
if (($per_page !== 'all' && !in_array((int) $this->per_page, $items_per_page_list, true))
  || ($per_page === 'all' && !in_array($this->per_page, $items_per_page_list, true))) {
     $per_page = reset($items_per_page_list);
}

```
It could be fixed using key_exists instead of in_array.

```
if (($per_page !== 'all' && !key_exists((int) $this->per_page, $items_per_page_list))
  || ($per_page === 'all' && !key_exists($this->per_page, $items_per_page_list))) {
     $per_page = reset($items_per_page_list);
}
```

If this is acceptable fix then I would be glad if you put it in 5.x version as well.

Thank you

**Comment by xsuchy09** [comment]
Last 5.7 version (for Nette < v3) - v5.7.2 - still has this issue. There are new commits fixing this issue - pls release new version for Nette < v3 too. Thanks.

**Comment by paveljanda** [comment]
Could you please try branch `v5.x`? It should be fixed there. Thanks.

**Comment by xsuchy09** [comment]
There is an error:
`File: .../vendor/ublaboo/datagrid/src/DataGrid.php:2786`
`array_key_exists() expects exactly 2 parameters, 3 given`
array_key_exists has only 2 parameters, not 3 ...

**Comment by xsuchy09** [comment]
New issue https://github.com/contributte/datagrid/issues/851, fix here https://github.com/contributte/datagrid/issues/850 ...
