### ISSUE TITLE
Hideable columns is not working with disabled remember state

### ISSUE THREAD

**Issue by RiKap** [contributte/datagrid#836]
```
$grid->setRememberState(FALSE);
$grid->setColumnsHideable();
```

When you have this configuration, it will never hide columns, as session is disabled.
I think that it should work, beacuse in many cases I really don't need to remeber ordering of columns, pagination ...., but I need to hide some columns.

**Comment by paveljanda** [comment]
But hidden columns are stored in session. There is currently no possibility to store hidden columns in persistent GET parameters, sorry.

**Comment by RiKap** [comment]
@paveljanda Yeah I know, but it does not matter that it should not work. It should be able to store hidden columns without rememebring state of order, pagination ...
I will try to prepare PR. :)
