### ISSUE TITLE
CSS Bootstrap 3

### ISSUE THREAD

**Issue by JStika** [contributte/datagrid#839]
Jak se da grid upravit na vzhled CSS Bootstrap 3, jako ma https://github.com/o5/grido?

Dekuji za odpoved.

**Comment by paveljanda** [comment]
Datagrid should work with bootstrap 3 fine.

**Comment by JStika** [comment]
Je nekde ukazka?

**Comment by paveljanda** [comment]
https://github.com/planette/playground/tree/master/contributte-datagrid

And try to use different assets (bootstrap 4 -> 3).

**Comment by JStika** [comment]
Dekuji za link. 
Zel, docker jeste nepouivam (sedim na windows 10 se skvelym PhpStorm).

**Comment by paveljanda** [comment]
You don't have to use docker, it is there only for the purpuse of using some database. Also, please write GitHub issues in EN. Thanks a lot. :)

**Comment by JStika** [comment]
Thanks for your info, time, and good will.
