### ISSUE TITLE
TypeError with current version of Naja

### ISSUE THREAD

**Issue by rozsival** [contributte/datagrid#859]
I am trying to use `contributte/datagrid` with the current version of `naja` and I get following error:

`Uncaught TypeError: naja.addEventListener(...).bind is not a function`.

The error is thrown in every `naja` extension of `datagrid`, both in production and development.

**Environment:**

`naja: 1.7.0`
`datagrid: 6.2.5`
`webpack: 4.41.2`

Since I am using `webpack` as  module bundler and `datagrid` assets are not modules and expect `naja` to be globally available, my `naja` setup looks as follows:

**naja.ts**
```typescript
import naja from 'naja';

// extensions registered

window.naja = naja;
document.addEventListener('DOMContentLoaded', naja.initialize.bind(naja));

export default naja;
```

**index.ts**
```typescript
import './naja';
import 'bootstrap-datepicker';
import 'bootstrap-select';
import 'ublaboo-datagrid/assets/datagrid';
import 'ublaboo-datagrid/assets/datagrid-instant-url-refresh';
import 'ublaboo-datagrid/assets/datagrid-spinners';
```

Any suggestions?

**Comment by rozsival** [comment]
I also tried including `naja` directly via `script` tag as an UMD and it does not work either. Same error.

**Comment by dakorpar** [comment]
@rozsival it's because naja is loaded after datagrid. Try loading naja before.

**Comment by rozsival** [comment]
@dakorpar No, it's not. You can see my `naja.ts` entry is the top-most loaded module included *before* datagrid assets. Also, if `naja` is not present when datagrid extension are registered, an exception is thrown clearly stating that `naja` or `nette.ajax.js` must be loaded first. That is not the issue. The `addEventListener` function is executed, the `bind` function on it causes the `TypeError`.

**Comment by rozsival** [comment]
@dakorpar Ok, maybe you meant the `DOMContentLoaded` event listener?

**Comment by rozsival** [comment]
@dakorpar Geeeez, so `naja` must be included *and* initialized too 🙈 That is so wrong as it does not correspond with `naja` docs. Extensions should be registered *before* `naja` init. It would be much better if datagrid assets were exposed as a module so a developer can register them on per-project basis. But in this case I understand the main aim of `naja` support was to really make it work instead of rewriting the assets so it was done as some kind of a wrapper around previously used `jQuery` extensions. Thanks for the help!

**Comment by paveljanda** [comment]
@rozsival Writing datagrid as npm module is planned. :)

**Comment by rozsival** [comment]
@paveljanda Thanks for the reply and your effort! You've done an amazing job with this project. Maybe I could help with the assets being rewritten as a module?

**Comment by paveljanda** [comment]
@rozsival Oh that would be amazing! I started with library happy (those nice checkboxes - https://github.com/paveljanda/happy). That one is required by datagrid and already is written using modules. I am not a frontend programmer so I hope I did a decent job. :D

I would appreciate some help as I am new to JS modules. :)

Are you able to send a full PR with datagrid rewritten as module? Will it break any backwards compatibility?

**Comment by f3l1x** [comment]
I would go to TypeScript if we decide to full-ground-rewrite.

**Comment by paveljanda** [comment]
@f3l1x I am not strictly against it. I am just voting for simplicity and usability. RIght now, it's no problem just to include the assets in html and datagrid just works out of the box. As far as I know, mentioned library **happy** works also in browser out of the box because it's in JavaScript (but still a module).

What advantages does TypeScript give us over plain JavaScript?

**Comment by rozsival** [comment]
@paveljanda I suppose I would be able to send a full PR, but I'm afraid I'm not able to answer your question about the BC at the moment. I'm able to get into it in  mid-January/February, so I'll get back  to you on this topic.

@f3l1x For sure! I finally migrated from Flow to TypeScript and there's no way back for me now 😄

**Comment by rozsival** [comment]
@paveljanda It's the type checking what makes TS much better over plain JS. The TS compiler is able to discover so many weak spots and potential bugs in the code base, it also guides developers towards writing much more strict and predictable code, not to mention such cool features as code completion, type guards and many more.

**Comment by f3l1x** [comment]
For my point of view it's easy to do codereview and faster accept changes without worries about break all stuff. :-) Just like PHPStan and Nette\Tester.

**Comment by paveljanda** [comment]
@rozsival Good point. Also January/Fabruary is absolutely fine. It's opensource, right? :D

Okey, let's go for it. How will it work with some dist assets? Will be there some dist code generated it the repo?

How does it work for users who want to contribute to the project?

1. User will fork the repo
2. User will make appropriate changes to the TS code
3. User will have to generate also the dist code? Or will it be done somehow automatically?

Sorry for being noob in this case. :)

**Comment by f3l1x** [comment]
I just place it here, awk. 

https://www.pika.dev/

**Comment by rozsival** [comment]
I am not familiar with the Pika Registry. On my projects, there are mostly two ways of doing it.

1) Dist assets are automatically built while publishing to npm registry, so only the source assets are included in the repo. However, in case of such repositories as datagrid, where code base might be distributed through multiple package managers (composer and npm), this might be a disadvantage as some developers might want to include dist assets from `vendor` dir if their project does not use npm modules. So there is the second approach.

2) Dist assets are built and included in the repo. The npm publish process just uses those "pre-built" assets. The build process might be done in a CI (Travis or other) or in a hook being executed on certain operations (merge, push etc.). It really depends on what suits the project and its collaborators the most.

**Comment by jiripudil** [comment]
To get back to the original issue: I don't understand why the `bind` is there in the first place 🤔

```js
naja.addEventListener('init', function (params)  {
    init(params.defaultOptions);
}).bind(this);
```

[`addEventListener`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) always returns `undefined`. Wasn't the `bind` meant for the event listener itself? Like this:

```patch
  naja.addEventListener('init', function (params)  {
      init(params.defaultOptions);
- }).bind(this);
+ }.bind(this));
```

In which case it's not even necessary because the listener function does not reference `this` at all.

I don't know what's the intention behind this, but if it's just a typo (I suspect it is), this should be an easy fix :)

cc @rozsival @paveljanda

**Comment by paveljanda** [comment]
@jiripudil If I understand the issue correctly, the only problem is in calling the `bind(this)`? I think there is no point in binding this event correctly to the inner scope - as you mentioned.

**Comment by paveljanda** [comment]
See https://github.com/contributte/datagrid/commit/2b70513d1ac746b8399ab735578831eaa760c065

**Comment by janvacek** [comment]
Thank you! but you fixed it only in `datagrid.js`, but `datagrid-spinners.js` still have this problem - https://github.com/contributte/datagrid/blob/master/assets/datagrid-spinners.js#L17

can you please fix it too?

@paveljanda

**Comment by paveljanda** [comment]
@janvacek Thanks for the reminder. `6.2.7`!

**Comment by rozsival** [comment]
@paveljanda Hey there! I think it's about time to rewrite datagrid assets. Honestly, while using it in my TypeScript / Naja based projects, I am facing more or less frustrating issues that can be resolved, but I am not happy at all about *how* they are being resolved currently.

So to start with rewriting, I would first like to know, if I could be provided with some full-featured datagrid demo project where I could map all features that need to be included in the new assets version. The current version of `datagrid.js` is kinda hard to read, so I don't want to miss out anything.

To quickly sum up the plan:

* TypeScript will be used
* All features will be divided into separated modules for better maintenance and further development (no single file of hundreds of lines of code)
* No more `jquery` and `nette.ajax.js`, everything will be powered by Naja
* There will be a top-level module that will be exported as an extension to be registered with Naja, this top-level module will bind and run all separated modules as needed
* Everything will be bundled with webpack into two files:
    * an ES module with the resulting Naja extension (without naja itself, developers will use this in their own naja setup)
    * a single UMD file (including naja with datagrid registered, intended to be used by developers who do not use module bundlers or do not want to setup naja themselves)
