### ISSUE TITLE
Group actions do not work with netteForms.js 3

### ISSUE THREAD

**Issue by radekdostal** [contributte/datagrid#882]
Datagrid requires nette/forms 3, but group actions (comboboxes) work with netteForms.js 2.4 only. Version 2.4 uses in toggle() style.display, but v3 uses hidden attribute.

**Comment by paveljanda** [comment]
I will have a look at that

**Comment by elring** [comment]
See my (misclosed) PR #830

**Comment by dakorpar** [comment]
@paveljanda ping? it's kinda critical bug and was working fine on before v6.0

**Comment by f3l1x** [comment]
Hey @dakorpar. PR #830 is closed. It's so hard to find what should be merged. Please tell me what to do or open a new one. Where we can discuss it. Thanks man.

**Comment by elring** [comment]
I by my mistake closed the PR #830. So I now made new one - #891. I have to use this patch in all my Nette + Datagrid projects.

**Comment by f3l1x** [comment]
Merged. Thx.
