### ISSUE TITLE
Online demo is broken

### ISSUE THREAD

**Issue by MagnificientLlama** [contributte/datagrid#886]
I am currently getting 404 error of your hosting from any page aside the basic one in the online demo.

**Comment by paveljanda** [comment]
What hosting do you mean?

**Comment by MagnificientLlama** [comment]
The online demo page you have at: https://examples.contributte.org/packages/datagrid/
the basic page works, any other shows to me this:
![404](https://user-images.githubusercontent.com/37192877/76851819-3e480f80-684a-11ea-8b98-4e0ea00e3dc5.png)

**Comment by f3l1x** [comment]
Fixed.
