### ISSUE TITLE
Bower is no longer supported

### ISSUE THREAD

**Issue by camohub** [contributte/datagrid#887]
Hi, as you know Bower is no longer supported. Please make an npm package with all dependencies. I don't use Bower any more and if I install Ublaboo via npm there are no dependencies mentioned in documentation. Thanks.

https://github.com/contributte/datagrid/pull/884 Do not support Bower but NPM. Few days ago you did a patch but only for Bower. Like Bower is still alive. But it is not. Bower is DEAD.

**Comment by f3l1x** [comment]
HI @camohub.

We have NPM package - https://www.npmjs.com/package/ublaboo-datagrid.

We will get rid off Bower, don't worry.

**Comment by camohub** [comment]
The point is you made a tag with bug fix BUT only for Bower not for NPM.  The secnd thing is package.json has no dependencies.  So why? https://github.com/contributte/datagrid/pull/884

**Comment by f3l1x** [comment]
PR: #892 

NPM tag: https://www.npmjs.com/package/ublaboo-datagrid/v/6.2.11

**Comment by camohub** [comment]
Thanks a lot. And what about dependencies? NPM is not priority for you?

**Comment by paveljanda** [comment]
@camohub will be added to readme in following days

**Comment by paveljanda** [comment]
https://github.com/contributte/datagrid/pull/892#issuecomment-615856485
