### ISSUE TITLE
Documentation mistake for Nextras\Orm

### ISSUE THREAD

**Issue by camohub** [contributte/datagrid#888]
Hi, you have a mistake in documentation https://contributte.org/packages/contributte/datagrid/data-source.html#nextrasdatasource for Nextras\ORM filter text example. **andWhere()** does not support arrays but **two string params.** like `->andWhere('text1 LIKE %s', "%$value%") ` Am I right? If so update it please Nextras\Orm is the best thing in Nette world for the last years. It should be documented correctly to support users to use it...

**Comment by camohub** [comment]
I made a PR https://github.com/contributte/datagrid/pull/889

**Comment by f3l1x** [comment]
Merged. Thx.
