### ISSUE TITLE
StringConfirmation with Naja - cant cancel

### ISSUE THREAD

**Issue by darkWolf-PR** [contributte/datagrid#899]
I´m using Datagrid with Naja and when adding StringConfirmation to addAction like:

```php
        $grid->addAction('delete', 'admin.delete', 'delete!')
             ->setIcon('trash')
             ->setTitle('admin.delete')
             ->setClass('btn btn-xs btn-danger ajax')
             ->setConfirmation(
                 new StringConfirmation('admin.really_delete_item', 'name')
             );
```

It´s impossible to cancel action-it always submits handle and deletes item no matter what button I click in confirm alert. Like it´s not recognizing the cancel action.

Datagrid: 6.2.17 - updated today by composer from I think 6.2.11(also didn´t work, that´s why I tried to update), manually updated scripts/css from assets folder(not using npm/etc.).
Naja: 1.7
jQuery, Bootstrap4: actual versions

Naja initialized like this(from Naja author Jan Pudil):
document.addEventListener('DOMContentLoaded', naja.initialize.bind(naja));

Other javascript/ajax like filtering, pagination etc. works as expected so I guess there shouldn´t be a problem with Naja init.

**Comment by paveljanda** [comment]
Closed (#900)
