### ISSUE TITLE
Naja 2.0 compatibility

### ISSUE THREAD

**Issue by sasule** [contributte/datagrid#913]
Datagrid.js is not Naja2.0 compatible. 
When using Naja2.0 error "missing function initialize" is shown.

**Comment by rozsival** [comment]
Hey guys, I just opened #927 which would add `naja:2.0` support.

**Comment by rozsival** [comment]
@paveljanda @sasule This is fixed in `v6.4.0`, we can close this issue.

**Comment by paveljanda** [comment]
👍 thanks @rozsival
