### ISSUE TITLE
A PHP notice occurs when rememberState is set to false

### ISSUE THREAD

**Issue by petaak** [contributte/datagrid#934]
After updating to the new version (v6.5.0) I'm getting a PHP notice when rememberState is set to false

My code:
```php
    public function createComponentGrid(): DataGrid
    {
        $grid = new DataGrid();

        $grid->setDataSource([
            ['id' => 1, 'name' => 'John', 'surname' => 'Doe'],
            ['id' => 2, 'name' => 'Jane', 'surname' => 'Smith'],
        ]);

        $grid->addColumnText('name', 'Name')->setSortable();
        $grid->addColumnText('surname', 'Surname')->setSortable();

        $grid->setRememberState(false);

        return $grid;
    }
```
ends up with a notice "Trying to access array offset on value of type null" on this line https://github.com/contributte/datagrid/blob/v6.5.0/src/DataGrid.php#L2779

**Comment by martinvenus** [comment]
If necessary I can support solving this issue by some $. Just give me know. Thanks.

**Comment by paveljanda** [comment]
Thanks, fixed: https://github.com/contributte/datagrid/releases/tag/v6.5.1
