### ISSUE TITLE
PHP 8 is not supported on composer

### ISSUE THREAD

**Issue by real-antonin** [contributte/datagrid#935]
If you try to install datagrid on composer the message will pop up.

`contributte/application v0.4.1 requires php ^7.2`

For now is nice workaround use composer [aliases](https://getcomposer.org/doc/articles/aliases.md).

**Comment by paveljanda** [comment]
This Pull request is fixing it: https://github.com/contributte/datagrid/pull/933
Please follow that PR, thanks 👍

**Comment by pkristian** [comment]
Hi, it quite doesn't,
PR is merged, but Issue is still present

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - ublaboo/datagrid[v6.5.0, ..., v6.5.1] require contributte/application ^0.4.1 -> satisfiable by contributte/application[v0.4.1].
    - contributte/application v0.4.1 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires ublaboo/datagrid ^6.5 -> satisfiable by ublaboo/datagrid[v6.5.0, v6.5.1].
```

it worked thou with ` --ignore-platform-reqs` which is not clean at all i think

**Comment by f3l1x** [comment]
Hi @pkristian. It should be fixed https://github.com/contributte/datagrid/releases/tag/v6.6.0

**Comment by pkristian** [comment]
@f3l1x it indeed is :heart:  thank you, updating now :heart_eyes:
