### ISSUE TITLE
GroupAction is not processed on Nette\Forms 3.1

### ISSUE THREAD

**Issue by BigOHenry** [contributte/datagrid#950]
With datagrid version 6.6.1/dev-master and Nette\Forms 3.1.0 there is no possible to submit GroupActions.

Issue is in Ublaboo\DataGrid\GroupAction\GroupActionCollection in method at line 170 - 177:

```
		$values = (array) $form->getValues();
		$values = $values['group_action'];

		if (
			($submitter->getName() === 'submit' && $submitter->isSubmittedBy())
			 && ($values->group_action === 0 || $values->group_action === null)) {
			return;
		}
```

`getValues` do not return group_action control with value.

**Possible reason:**
At release notes of Nette\Forms 3.1.0: _Form::getValues() returns only controls in scope (BC break)_

**Comment by paveljanda** [comment]
Thanks for the info. I am not a fan of Nette releasing BC breaks in minor version. :/ Uff.

**Comment by vodictomas** [comment]
Can you please check referenced PR, if this issue can be fixed this way?

**Comment by paveljanda** [comment]
New datagrid now requires nette/forms ^3.1.3. See https://github.com/contributte/datagrid/releases/tag/v6.8.0
