### ISSUE TITLE
Nette Application 3.1.1 incompatibility

### ISSUE THREAD

**Issue by otoman** [contributte/datagrid#951]
Datagrid 6.6.1 added to latte template {control reservationsGrid}
returns error _get_class(): Argument #1 ($object) must be of type object, null given_

**Possible reason - TemplateFactory::createTemplate() returns Nette\Bridges\ApplicationLatte (BC break)**

Same on 6.7.x-dev

**Comment by paveljanda** [comment]
Could you send me a tracy screen? I can not replicate this behaviour

**Comment by otoman** [comment]
I tried it now with Nette 3.1.2 and works fine. So I don´t know what was that...
