### ISSUE TITLE
Unable to convert CSV to windows-1250 - mb_convert_encoding()

### ISSUE THREAD

**Issue by grafickepracecom** [contributte/datagrid#956]
For a CSV to be readable by Czech Excel the windows-1250 encoding must be used. There is a demo in the [documentation](https://contributte.org/packages/contributte/datagrid/export.html#exportcallback).

However, the CSVResponse.php uses mb_convert_encoding() function which doesn't support windows-1250 encoding - see [here](https://www.php.net/manual/en/mbstring.supported-encodings.php).

The result is that the downloaded csv contains only lines with warning.

The quickfix solution is to change CSVResponse line #97 from
`				echo mb_convert_encoding($csvRow, $this->outputEncoding);
`
to
`				echo iconv('utf-8', $this->outputEncoding, $csvRow);
`

**Comment by elring** [comment]
I have exactly same problem. For Czech purposes CSV export is now almost unusable. 
But this seems to be bug of contributte/application CSVResponse, so it should be probably reported there :-)

**Comment by paveljanda** [comment]
Could anyone send a PR into contributte/application? :)

**Comment by elring** [comment]
I can do it, but I don't know the reason, why it was rewritten to mb_convert_encoding (part of UTF-16 corrections)...

**Comment by paveljanda** [comment]
Let's see the answer... https://github.com/contributte/application/pull/26#issuecomment-793964299
