### ISSUE TITLE
PHP warning in Tracy after filtering without pagination

### ISSUE THREAD

**Issue by radekdostal** [contributte/datagrid#961]
I have datagrid without pagination - setPagination(FALSE). After filtering, e.g. in text column or date range column - Nette\Forms\Container::getValues() invoked but the form is not valid - is shown in Tracy.

datagrid 6.8.0, nette/forms 3.1.3

**Comment by paveljanda** [comment]
Thx, https://github.com/contributte/datagrid/releases/tag/v6.8.1
